### ISSUE TITLE
Serialization of variable length datastructure

### ISSUE THREAD

**Issue by NicolasDorier** [LedgerHQ/btchip-js-api#1]
I'm not sure to post this issue here or on https://github.com/LedgerHQ/btchip-doc, but you don't document how you are encoding "variable length" structures.

I see from the code, that you seems to prepend the length of the data, which make sense, but have the disadvantage to crash if such data is more than 255 bytes long...

> return this.card.sendApdu_async(0xe0, 0x46, outputType, p2, data, [0x9000]).then(function (outData) { 
> 489                   var result = {}; 
> 490                   var scriptDataLength = outData.byteAt(0); 
> 491                   result['scriptData'] = outData.bytes(1, scriptDataLength); 
> 492                   result['authorizationRequired'] = (outData.byteAt(1 + scriptDataLength) == 0x01); 
> 493                   return result; 
> 494                 }); 

I'm not sure yes if that is a problem, but should I consider that every "var" data structure in https://ledgerhq.github.io/btchip-doc/bitcoin-technical.html
should be formatted as such, unless specified otherwise ? (data prepent by 1 byte length ?)

**Comment by btchip** [comment]
Hi

No, encoding is not really consistent along APDUs, in order to save some code space. 

Here the length is encoded on one byte the dongle will never send more for a regular output.

For other input structures, you don't have an additional length field added unless specified, but some data must be "streamed" stopping on the right elements due to parser limitations.

Let me know which structure needs more documenting.

**Comment by NicolasDorier** [comment]
Ok I see, I will when I hit some problem. I am currently reviewing the code and documentation, because we'll probably need to make a C# API for ledger soon.

**Comment by btchip** [comment]
Sure, I suck even more at C# than at Python or JS, so that's very welcome - don't hesitate to ask for any question.
